runJava: SwitchCases.class
	java SwitchCases

SwitchCases.class: SwitchCases.java
	javac SwitchCases.java

clean:
	rm *.class

save:
	git add *
	git commit *
	git push origin main

cleanSave:
	rm *.class
	git add *
	git commit *
	git push origin main